language: python
python:
  - "3.5"
  - "3.6"

install: pip install tox-travis
script: tox

deploy:
  provider: pypi
  skip_existing: true
  user: chrisgavin
  password:
    secure: "gARBrZmqVaw/yj4nbWmuR3f8M2gv6RSqMCoYIYaLszwIGiPem4xy4b3Vq1UbddTTJSnx27spsj+J6C8EbaN2WFBckhAB9KjKBfR2xuKZQTd8NmWUfVBQgZvODE/FnZzVbyPnaiuFyhOlLJlntu1/6ICjfUixMPDEoKF6xqseB7vKlMPOI4SWjuPmd6xEP+duJearTGuvl/PCXuKnoSPJQWpcely1Ku1SjNKxw0rNjINwDL4/jYqOJ08Cwt6GyF4poYIM+McSiymrIHEImHSExZWhRVaiGESoiHDgOuq0gNCHH4xXahYHO4DphLzhJypYLZ4dGU/4l6kaglhCd+WLFfHycjT4Icnn7wDvt4Xoqv+tAf1qrv3F2JuA8abwqTn0WtW+GV6B8pB1NfWuy66u4P7Vy4qkboQL4Mb9Zwi7f9k3/Urk4B0gexE5owW2+zkkeaHCr/MwFZ3Ma8MX434cIWM3lMnIzF2gaJKV17eyNOXvQxy9ewFEO605p1YZGiY7Z9rt/wVl1LGoQDzxcc3U1/K+j756qRCTDSgWt3JuwrQKaX16bjMOLWtwXpry9aMB1fVNN3lw9In1I65UdKUb4E/eSnwn9P9kVurKiSw7vioDptOHw5OgDaGDawf5JRCcAkEOFHoLSvZlZdnSgj+kesyJZf2Iq/jL1huEF4YRZEw="
  on:
    tags: true

notifications:
  slack:
    secure: "AG8jMMhUgP4Wu4uHW51qKOSdq0sgzhARFZPvJZpD00eZqKyK2Ie/hy4SWAEdNhpo6sweJxkwH/joCI9Bla5nfHYyd+3kFBZvUs4EzntjF5+X/XmxBq1cAMkI0R65i8T2PKfDaXODDLbcTThcOeCkWqEMNTJL22GgMEF+SKoqbUt9v6HeWctYy20etKhUWPwDagYhLJbuMSDPLMnSj/doUcyohj7eGfGNVhXEl1IL4wh7qLW/sfs3oEZnqO+yy5JO6+B6pIU8PNzVYG7KJQE2Rk8itvGT3KjhjbTqPF+eUy1vfuVvfRZKfk8QREmOi25gfoJ0YNyV8q6R73xMHnEUNUsJ+za6+FBONu6OnerlErrDyJbiNxKbKlk/sTqXtB4xhOJBSKr21rOPUCaZIQ6tNXSHg57ZnmVKIaWJHsLvVOnyAbLjJUGakwQn3NI7HBCmDo0CpkHYzcYrWRBdrCr1nqMIlLb3AHIFdnLst4nOcccYkfCh3bOnHWIRyXQ60dgCzpmEJ5/sJP167+Wp165Uz79YWpsibBBMhIVt/WDl60N2rfeHQZ9Jne+osj6qereQ229KGhmLt+JXfSL7JbI02M9aQSSyeGuYgCuDyXUD1Te/UHNoD1QHtVztI3sYixgyLKPTOZdrA06r0XCkvRb5+H86MxvoNsqzWOg8bfp79A0="
